name: Deploy Infrastructure and App

on:
  push:
    branches:
      - main

jobs:
  deploy_everything:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Apply AWS Infrastructure
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: Build and Run Docker Container
        run: |
          docker compose down
          docker compose up -d --build