name: Deploy Node.js App to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SSH into VPS and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script: |
            # Navigate to application repository directory
            cd ~/node-github-actions-demo || exit 1

            # Fetch the latest changes from GitHub
            git checkout main
            git pull origin main

            # Rebuild and restart containers using Docker Compose
            docker compose down
            docker compose up -d --build